Feat/add dal
kysect/Quewer pull request #9
Opened 2021-03-05 18:10 UTC by InRedikaWB

2021-03-06 18:02 UTC, s4xack requested changes

2021-03-06 18:02 UTC, s4xack commented on Source/Quewer.Core/DataAccess/IQuewerDbContext.cs
> +        DbSet<QueQueamQueser> QueQueamQuesers { get; set; }
не уверен что нужна эта табличка в контексте, это же просто many to many Que и QueamQusers

2021-03-06 18:02 UTC, s4xack commented on Source/Quewer.Core/Models/Que.cs
> +        public virtual Queam Queam { get; set; }
а в чем собственно заключается идея сделать все проперти с моделями виртуальными?

2021-03-06 18:02 UTC, s4xack commented on Source/Quewer.Tests/QueCommonTest.cs
> +        public void Test1()
Ну можно было и переименовать ради приличия...

2021-03-07 09:42 UTC, InRedikaWB commented on Source/Quewer.Core/DataAccess/IQuewerDbContext.cs
> +        DbSet<QueQueamQueser> QueQueamQuesers { get; set; }
А разве еф уже умеет сам их делать?)

2021-03-07 09:43 UTC, InRedikaWB commented on Source/Quewer.Core/Models/Que.cs
> +        public virtual Queam Queam { get; set; }
tl;dr нужно для лейзи лоадинга
https://docs.microsoft.com/en-us/ef/ef6/querying/related-data#lazy-loading

2021-03-07 11:07 UTC, s4xack commented on Source/Quewer.Core/DataAccess/IQuewerDbContext.cs
> +        DbSet<QueQueamQueser> QueQueamQuesers { get; set; }
давно
я даже открыл Jinder и перепроверил

2021-03-07 11:09 UTC, s4xack commented on Source/Quewer.Core/Models/Que.cs
> +        public virtual Queam Queam { get; set; }
умно

2021-03-08 15:14 UTC, InRedikaWB commented on Source/Quewer.Core/DataAccess/IQuewerDbContext.cs
> +        DbSet<QueQueamQueser> QueQueamQuesers { get; set; }
Там есть еще PushTime. Т.е. там есть доп инфа о записи.

2021-03-09 07:27 UTC, merged